// <auto-generated />
namespace DAL.AppIdentityDbMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initialized1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialized1));
        
        string IMigrationMetadata.Id
        {
            get { return "202101212044567_Initialized1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
